"""empty message

Revision ID: 3b23235c6339
Revises: None
Create Date: 2014-04-09 20:44:04.180885

"""

# revision identifiers, used by Alembic.
revision = '3b23235c6339'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
