"""empty message

Revision ID: 3ce2a1e63d32
Revises: None
Create Date: 2014-04-17 10:51:10.212888

"""

# revision identifiers, used by Alembic.
revision = '3ce2a1e63d32'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muzik',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('artist', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('beat', sa.String(length=50), nullable=True),
    sa.Column('tempo', sa.String(length=50), nullable=True),
    sa.Column('energy', sa.String(length=50), nullable=True),
    sa.Column('danceability', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('loudness', sa.String(length=50), nullable=True),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('time_signature', sa.String(length=50), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('muzik')
    ### end Alembic commands ###
